### ISSUE TITLE
GTK Issue

### ISSUE THREAD

**Issue by nvdl** [lanceman2/quickplot#3]
win.c:43:29: fatal error: imgGrabCursor.xpm: No such file or directory

I am using Debian 8.

Any pointer?

**Comment by lanceman2** [comment]
./configure --enable-developer

I get the exact same error when I do not set that configure option.

--enable-developer is required when building from repo source.  It has more dependences when building from repo source.  For example I do not check in the imgGrabCursor.xpm file into the repo because I can generate it from  imgGrabCursor.png via imagemagick's convert program; But when I make a source tarball I include that generated file.

All the stupid warnings for from GTK+3 being a moving target.  I'm thinking of going back to GTK+2 which I think is maintained and still used by many projects.

**Comment by lanceman2** [comment]
./configure --enable-developer

for repo source building.  See github ticket comments.

cheers
lance

**Comment by nvdl** [comment]
Worked. Cheers.
